version: "3"

services:
  db:
    image: postgres:17.5
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    networks:
      - teqnet
    volumes:
      - teqgo-db:/var/lib/postgresql

volumes:
  teqgo-db:

networks:
  teqnet: